# Site settings
title: "Researcher's Homepage"
description: "Academic Homepage"
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Data files
data_dir: _data

# Plugins
plugins:
  - jekyll-feed

# Default layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
